### ISSUE TITLE
Docker image and k8s manifest for mvp-icap-service

### ISSUE THREAD

**Issue by faisaladnanpeltops** [filetrust/k8-performance-use-cases#11]
Can you create a docker image and k8s manifest (Pod or Deployment) that can run mvp-icap-service on local minikube.
See https://github.com/filetrust/mvp-icap-service

**Comment by hongson1981** [comment]
@faisaladnanpeltops 
I see that this issue is blocker of another issue, Can we resolve it first ? I can do it quickly
My steps below :
Install Docker Desktop and minikube
Pointing Docker to minikube environment
Create docker image follow docker file of task https://github.com/filetrust/mvp-icap-service
Create kubenetes point to local docker image in step above 
Is that right ?
